### ISSUE TITLE
Inconsistent LPIPS implementation?

### ISSUE THREAD

**Issue by sunset1995** [creiser/kilonerf#8]
Really great work!

I have a question about current LPIPS implementation.
From the [`lpips` document](https://github.com/richzhang/PerceptualSimilarity), the input RGB images should be in scale `[-1,+1]`.
But it seems that the current implementation feed RGB in `[0, 1]` to `lpips`.

I have also traced the baseline `NSVF`'s lpips evaluation and they scale the RGB from `[0, 1]` to `[-1, 1]` (see [their code](https://github.com/facebookresearch/NSVF/blob/12e63e71243a3fd0f90a953626b0c98c95687aa0/fairnr/models/fairnr_model.py#L296)).

I would appreciate clarification about this.
Thanks!

**Comment by creiser** [comment]
Thanks for pointing this out. I will fix that and change the numbers if there is any deviation from the different range. I suspect if there is any deviation it will be very small.
